MagaluCloud/magalu

- LICENSE
- mgc/LICENSE
- mgc/terraform-provider-mgc/LICENSE
Adds licensing files for Terraform provider (MPL2) and all the rest (GPL3)
> chore: add licensing files

- mgc/terraform-provider-mgc/docs-extra/guides/k8s-cluster-creation.md
- mgc/terraform-provider-mgc/docs/guides/k8s-cluster-creation.md
Add guide in TF docs about the required scopes for K8s cluster creation.
> docs: add TF guide for k8s scopes

- mgc/terraform-provider-mgc/docs-extra/guides/k8s-cluster-creation.md
- mgc/terraform-provider-mgc/docs/guides/k8s-cluster-creation.md
Fixes typo on terraform docs guide. 
Yeah, I know...
> fix: typo on TF k8s cluster creation guide

- .github/pull_request_template.md
Adds a pull requests template to the repository.
N/A
Github-related, hard to test before merge.
> chore: add PR template to repo

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- goreleaser_cli.yaml
When create a new CLI release the new version should be a PR in the mgc-cli repository.
n/a
n/a
- [ x Corresponding changes to the documentation were made
n/a
> chore: cli release with pr

- mgc/terraform-provider-mgc/mgc/resources/mgc_k8s_nodepool.go
This pull request includes updates to the `mgc_k8s_nodepool` resource in the Terraform provider for MGC. The changes improve validation and handling of node pool replica parameters.
* Added the `int64validator` and `validator` imports to support new validation features. (`mgc/terraform-provider-mgc/mgc/resources/mgc_k8s_nodepool.go`)
* Added validators to ensure `replicas`, `max_replicas`, and `min_replicas` are at least 0. (`mgc/terraform-provider-mgc/mgc/resources/mgc_k8s_nodepool.go`)
* Refactored the `Create` method to properly handle cases where `max_replicas` or `min_replicas` are not set, ensuring auto-scaling parameters are correctly initialized only when necessary. (`mgc/terraform-provider-mgc/mgc/resources/mgc_k8s_nodepool.go`)
*  …
> feat: tf - remove nodepool validation

- .github/pull_request_template.md
This pull request updates the pull request template to improve clarity and provide more structured guidance for contributors. The changes focus on reorganizing sections, adding examples, and enhancing the testing documentation.
Improvements to the pull request template:
* Updated the "Description" section to "What does this PR do?" and added an example to guide contributors in providing a clear and concise description of their changes.
* Added a new "How Has This Been Tested?" section with subsections for unit tests, integration tests, and manual testing, including examples to help contributors describe their testing process in detail.
* Enhanced the "Checklist" section to ensure contributors follow project style guidelines, run pre-commit checks, and add necessary documentation and …
> chore: pr template update

- mgc/cli/cmd/output.go
- mgc/cli/go.sum
> fix: adjust output default 

- mgc/terraform-provider-mgc/mgc/resources/mgc_bs_volumes.go
This pull request includes changes to the `mgc/terraform-provider-mgc/mgc/resources/mgc_bs_volumes.go` file, focusing on enhancing the functionality and improving the code quality. The most important changes include adding plan modifiers to the `snapshot_id` attribute and updating the state with the snapshot ID during resource creation.
https://chat.google.com/room/AAAAT0-WOyc/b0aQREl_5hM/b0aQREl_5hM?cls=10
> fix: tf - block storage - volume

- .github/workflows/upload-docs.yaml
update upload-docs workflow to trigger on workflow_dispatch
> chore: update upload-docs workflow to trigger on workflow_dispatch

- mgc/terraform-provider-mgc/mgc/resources/mgc_bs_volumes.go
- mgc/terraform-provider-mgc/tests/block-storage/main.tf
feat: allow tf bs volumes perform update in name field 
ok
ok
> feat: tf block storage volumes now allow rename

- mgc/terraform-provider-mgc/mgc/resources/mgc_vm_instances.go
> chore: retain the same image and machine type when only the server-side name is changed

- mgc/terraform-provider-mgc/docs/resources/dbaas_instances.md
- mgc/terraform-provider-mgc/docs/resources/virtual_machine_instances.md
- mgc/terraform-provider-mgc/examples/resources/mgc_dbaas_instances/import.sh
- mgc/terraform-provider-mgc/examples/resources/mgc_virtual_machine_instances/import.sh
- Removing import example for resources that not yet support
> chore: removing import example for resources that not yet support

- mgc/cli/cmd/log_debug.go
- mgc/core/http/http_logger.go
- mgc/core/http/http_retry.go
This PR modifies the behavior of the --debug flag in the CLI.
Before this change, using the flag resulted in a large amount of unnecessary content being displayed, significantly impairing the usability of this feature.
With this update, the default log level has been changed to info, and only a few critical points in the code were updated from debug to info. As a result, the debug output has been simplified.
If a more detailed debug level is still required, the MGC_SDK_LOG_DEBUG environment variable can be used to set a different log level (available options: fatal, error, debug, and info).
- **Manual Testing**: Explain the …
> feat: cli - change debug flag

- mgc/sdk/static/object_storage/common/const.go
This PR up the min chunk size to 200mb
Manually tested with small and large uploads, no issues
- [  ] I have run Pre commit `pre-commit run --all-files`
- [  ] My code follows the style guidelines of this project
- [  ] I have made corresponding changes to the documentation
- [  ] I have added tests that prove my fix is effective or that my feature works
> feat: improve min chunk size

- mgc/sdk/static/auth/api_key/scopes.json
> feat: cli - add container registry api scope

- mgc/terraform-provider-mgc/mgc/datasources/mgc_dbaas_instances_snapshots.go
- mgc/terraform-provider-mgc/tests/dbaas/main.tf
fix dbaas list snapshots missing property
ok
ok
> fix: dbaas list snapshots missing property

- mgc/terraform-provider-mgc/mgc/resources/mgc_k8s_nodepool.go
> fix: tf - k8s - update nodepools

- mgc/sdk/sdk.go
> chore: prepare http roundtripper to accept new userAgent

- mgc/cli/docs/kubernetes/cluster/create/help.md
- mgc/cli/docs/kubernetes/nodepool/create/help.md
- mgc/cli/docs/kubernetes/nodepool/update/help.md
- mgc/sdk/openapi/openapis/dbaas.openapi.yaml
- mgc/sdk/openapi/openapis/index.openapi.yaml
- mgc/sdk/openapi/openapis/kubernetes.openapi.yaml
- mgc/sdk/openapi/operation_table.go
- mgc/spec_manipulator/cli_specs/container-registry.openapi.yaml
- mgc/spec_manipulator/cli_specs/database.jaxyendy.openapi.yaml
- mgc/spec_manipulator/cli_specs/events-consult.openapi.yaml
- mgc/spec_manipulator/cli_specs/kubernetes.jaxyendy.openapi.json
- mgc/spec_manipulator/cli_specs/network.jaxyendy.openapi.json
- mgc/spec_manipulator/cli_specs/virtual-machine.jaxyendy.openapi.json
- openapi-customizations/kubernetes.openapi.yaml
> feat: core - change operation

- mgc/cli/docs/block-storage/snapshots/help.md
- mgc/sdk/openapi/openapis/block-storage.openapi.yaml
- mgc/spec_manipulator/cli_specs/block-storage.jaxyendy.openapi.json
- mgc/spec_manipulator/cli_specs/conv.block-storage.jaxyendy.openapi.json
Adds copy feature to volumes snapshots in Block Storage
- **Manual Testing**:  Command execution, documentation and auto-complete features were tested.
> feat: add copy command to volumes snapshots

- mgc/cli/docs/auth/clients/create/help.md
- mgc/cli/docs/auth/clients/update/help.md
- mgc/sdk/static/auth/clients/common.go
- mgc/sdk/static/auth/clients/create.go
- mgc/sdk/static/auth/clients/update.go
> feat: update auth-client idm

- .github/workflows/ci.yaml
- .github/workflows/internal.yaml
- .github/workflows/release.yaml
- .pre-commit-config.yaml
> fix: go.version in pipeline

- mgc/cli/docs/virtual-machine/images/list/help.md
- mgc/cli/docs/virtual-machine/instances/create/help.md
- mgc/cli/docs/virtual-machine/instances/get/help.md
- mgc/cli/docs/virtual-machine/instances/list/help.md
- mgc/sdk/openapi/openapis/virtual-machine.openapi.yaml
- mgc/spec_manipulator/cli_specs/conv.virtual-machine.jaxyendy.openapi.json
- mgc/spec_manipulator/cli_specs/virtual-machine.jaxyendy.openapi.json
> feat: vm - add volumes on instance create

- .pre-commit-config.yaml
- mgc/core/http/http.go
- mgc/core/http/http_test.go
- Error output for CLI now retorn the mgc trace id
- Error output layout improved
> feat: mgc trace id added to error output

- mgc/cli/docs/virtual-machine/instances/create/help.md
- mgc/sdk/openapi/openapis/virtual-machine.openapi.yaml
- mgc/spec_manipulator/cli_specs/conv.virtual-machine.jaxyendy.openapi.json
- mgc/spec_manipulator/cli_specs/virtual-machine.jaxyendy.openapi.json
> chore: update vm spec

- mgc/core/http/http.go
- Improve the error layout for CLI
Example:
```sh
❯ ./mgc network ports get "asdgadsg"
Error:
Status: 404 Not Found - Port asdgadsg not found
Request ID: 04248b6d-ca1e-903a-b4b4-ec6b96fab766
MGC Trace ID: 97a63b96-971e-462c-9598-493a550e7fb8
{"message":"Port asdgadsg not found","error_code":422,"links":[{"href":""}]}
````
> feat: improve return error layout

- mgc/cli/docs/http/do/help.md
- mgc/cli/docs/http/json/delete/help.md
- mgc/cli/docs/http/json/get/help.md
- mgc/cli/docs/http/json/head/help.md
- mgc/cli/docs/http/json/options/help.md
- mgc/cli/docs/http/json/patch/help.md
- mgc/cli/docs/http/json/post/help.md
- mgc/cli/docs/http/json/put/help.md
- mgc/cli/docs/http/json/trace/help.md
- mgc/sdk/openapi/README.md
- mgc/sdk/openapi/openapis/audit.openapi.yaml
- mgc/sdk/openapi/openapis/block-storage.openapi.yaml
- mgc/sdk/openapi/openapis/container-registry.openapi.yaml
- mgc/sdk/openapi/openapis/dbaas.openapi.yaml
- mgc/sdk/openapi/openapis/kubernetes.openapi.yaml
- mgc/sdk/openapi/openapis/network.openapi.yaml
- mgc/sdk/openapi/openapis/virtual-machine.openapi.yaml
- mgc/sdk/static/http/common.go
- openapi-customizations/audit.openapi.yaml
- openapi-customizations/block-storage.openapi.yaml
- openapi-customizations/container-registry.openapi.yaml
- openapi-customizations/dbaas.openapi.yaml
- openapi-customizations/kubernetes.openapi.yaml
- openapi-customizations/network.openapi.yaml
- openapi-customizations/virtual-machine.openapi.yaml
- scripts/add_specs.sh
> feat: change region br-ne-1 to br-ne1

- Makefile
- mgc/cli/docs/network/security_groups/rules/create/help.md
- mgc/cli/docs/network/subnetpools/list/help.md
- mgc/cli/docs/network/subnets/update/help.md
- mgc/cli/docs/network/vpcs/create/help.md
- mgc/cli/docs/network/vpcs/help.md
- mgc/cli/docs/network/vpcs/ports/list/help.md
- mgc/sdk/openapi/openapis/index.openapi.yaml
- mgc/sdk/openapi/openapis/network.openapi.yaml
- specs/conv.network.jaxyendy.openapi.json
- specs/network.jaxyendy.openapi.json
> feat: update network specs

- mgc/sdk/sdk.go
- Change user-agent
- Now with info about the user os and cpu arch
- New template: 'MgcCLI/{version} ({os}; {arch})'
> chore: user-agent now has info about os and arch

- mgc/cli/cmd/root.go
> chore: update root.go

- mgc/cli/cmd/schema_flags/constraints.go
> fix: addXOfSchemaConstraints when spec has '- {}'

- Makefile
- mgc/spec_manipulator/cmd/spec/add.go
- mgc/spec_manipulator/cmd/spec/common.go
- mgc/spec_manipulator/cmd/spec/delete.go
- mgc/spec_manipulator/cmd/spec/downgrade.go
- mgc/spec_manipulator/cmd/spec/download.go
- mgc/spec_manipulator/cmd/spec/list.go
- mgc/spec_manipulator/cmd/spec/merge.go
- mgc/spec_manipulator/cmd/spec/prepare.go
- mgc/spec_manipulator/cmd/spec/root_spec.go
- scripts/add_specs.sh
- scripts/add_specs_without_region.sh
> fix: makefile indexgen

- mgc/cli/cmd/schema_flags/schema_flag_value.go
- mgc/cli/docs/config/set.md
- mgc/core/schema/schema.go
- mgc/core/schema/simplify_schema.go
- mgc/sdk/static/config/set.go
> fix: config set

- .github/workflows/release.yaml
> fix: change release.yaml

- .github/workflows/release.yaml
> change release.yaml

- .github/workflows/internal.yaml
- internal.yaml
- release.yaml
> fix: goreleaser configs

- release.yaml
- Fix the version prefix for the CLI set on the goreleaser
> fix: goreleaser set the version with prefix for vesrion

- mgc/cli/docs/object-storage/buckets/delete.md
- mgc/sdk/static/object_storage/buckets/delete.go
- mgc/sdk/static/object_storage/common/delete.go
Async Bulk Deletion
Added --recursive-async flag to bucket delete command
Sending new header to trigger bulk delete (async) when flag is set to true
Same batching logic, but returns immediately when --async is used
Maintains existing sync behavior (no breaking changes)
> feat(buckets): Bulk Delete command implementation

- mgc/cli/docs/object-storage/buckets/delete.md
- mgc/cli/main.go
> chore: change panic recover

- mgc/core/http/http.go
- mgc/core/http/http_test.go
> fix: convert JSON numbers to int

- mgc/cli/cmd/root.go
- mgc/cli/cmd/schema_flags/desc.go
- mgc/cli/docs/load-balancer/network-backends/get.md
- mgc/cli/docs/load-balancer/network-backends/replace.md
- mgc/core/schema/cow.go
- mgc/sdk/static/config/list.go
falhei na interpretação ao fazer o update do kin-openapi no pr #1348 
em desc.go era:
`if schema.Type == "" {`
e eu converti pra:
`if schema.Type != nil && len(schema.Type.Slice()) == 0 { `
e com o fix de agora foi pra:
`if schema.Type == nil || (len(schema.Type.Slice()) == 0) {`
olhando pro contexto da função, fica claro o meu erro =/ 
se o type for "" ou nil, é pq o schema tem algum anyOf, oneOf... e devemos atribuir isso no output
> fix: bug created on #1348

- mgc/sdk/static/object_storage/common/list.go
This PR fixes an issue with improperly escaping spaces when using the list objects comments (object storage)
- manually (by the developer)
```
➜  magalu git:(rafael/list-encode) ./dist/mgc_darwin_arm64_v8.0/mgc os objects list 'list-encode-test/subdir 1'
CommonPrefixes: []
Contents:
- ContentSize: 3424
Key: subdir 1/README.md
LastModified: "2025-04-17T22:44:57.979Z"
StorageClass: STANDARD
- ContentSize: 3424
Key: subdir 1/foo.md
LastModified: "2025-04-17T22:49:16.604Z"
StorageClass: STANDARD
```
Without the fix, this returns a signature error because we were encoding the `prefix` query string param with a '+' instead of a '%20' (as described by the [aws doc](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_sigv-create-signed-request.html)
- integration testing - using the object …
> fix: url encode on list objects

- mgc/sdk/static/object_storage/common/list.go
Includes a custom query string encoder for list api calls so that we handle spaces and other chars properly
```
➜  magalu git:(rafael/custom-query-string-encoder) ./dist/mgc_darwin_arm64_v8.0/mgc os objects list 'rafael-bruno-teste/subdir1/subdir2/'
CommonPrefixes:
- Path: subdir1/subdir2/subdir3 = teste/
- Path: subdir1/subdir2/subdir4=teste/
- Path: "subdir1/subdir2/subdir5 - teste/"
- Path: subdir1/subdir2/subdir6 + teste/
- Path: subdir1/subdir2/subdir7 * teste/
Contents:
- ContentSize: 3424
Key: …
```
> Use custom QueryString encoder for list operations

- mgc/sdk/static/object_storage/common/bigfile_downloader.go
corrige um erro no download all em que nao cria o path
download-all em um bucket "problematico" multiplas vezes
teste sera rodado no s3-specs
Testado manualmente em um bucket com problemas
> fix(objs): make dir on bigfile_downloader

- mgc/cli/cmd/schema_flags/parsers.go
- mgc/sdk/openapi/request_body_json.go
> fix: parse empty array

- mgc/cli/docs/virtual-machine/help.md
- mgc/cli/docs/virtual-machine/machine-types/help.md
- mgc/cli/docs/virtual-machine/machine-types/list.md
- mgc/sdk/openapi/openapis/virtual-machine.openapi.yaml
- mgc/spec_manipulator/specs.yaml
- specs/conv.virtual-machine.jaxyendy.openapi.json
- specs/virtual-machine.jaxyendy.openapi.json
- Added the machine types resource back to virtual machines menu
- Changed the VM specs endpoint to br-se-1
> chore: Return virtual machines with machine types resource

- mgc/cli/docs/network/ports/update.md
- mgc/spec_manipulator/cmd/pipeline/gen_expected_cli_doc_output.go
- mgc/spec_manipulator/cmd/pipeline/gen_expected_cli_doc_output_test.go
> feat: remove html from docs

- .github/workflows/ci.yaml
> fix: pipeline with forked repo

- mgc/cli/docs/container-registry/help.md
- mgc/cli/docs/container-registry/proxy-caches/create.md
- mgc/cli/docs/container-registry/proxy-caches/delete.md
- mgc/cli/docs/container-registry/proxy-caches/get.md
- mgc/cli/docs/container-registry/proxy-caches/help.md
- mgc/cli/docs/container-registry/proxy-caches/list.md
- mgc/cli/docs/container-registry/proxy-caches/status/create.md
- mgc/cli/docs/container-registry/proxy-caches/status/help.md
- mgc/cli/docs/container-registry/proxy-caches/status/list.md
- mgc/cli/docs/container-registry/proxy-caches/update.md
- mgc/sdk/openapi/openapis/container-registry.openapi.yaml
- specs/container-registry.openapi.yaml
> feat: update container registry

- .github/workflows/tests.yaml
- mgc/cli/cmd/handle_executor.go
- mgc/cli/cmd/root.go
> fix: flag loop

- mgc/cli/docs/dbaas/clusters/create.md
- mgc/cli/docs/dbaas/instances/create.md
- mgc/cli/docs/dbaas/snapshots/clusters-snapshots/restore.md
- mgc/cli/docs/dbaas/snapshots/instances-snapshots/restore.md
- mgc/sdk/openapi/openapis/dbaas.openapi.yaml
- mgc/sdk/openapi/openapis/index.openapi.yaml
- specs/database.jaxyendy.openapi.yaml
> feat: update dbaas

- mgc/cli/docs/kubernetes/cluster/create.md
- mgc/sdk/openapi/openapis/kubernetes.openapi.yaml
- specs/kubernetes.jaxyendy.openapi.json
- New K8s Cluster Field 
- CNI
> feat: added k8s cluster CNI field
