mgc/terraform-provider-mgc/mgc/resources/mgc_k8s_nodepool.go

Resolve an import error in the nodepools functionality by ensuring the ClusterID is correctly set during the import state process.

[tf] fix: Fix nodepools import error

---

.github/workflows/release.yaml

Limpa o diretório de documentação gerada para TF toda vez que as docs forem geradas.
Isto foi feito para evitar que recursos removidos sigam com documentação e apareçam no registry do Terraform (ex.: https://registry.terraform.io/providers/MagaluCloud/mgc/latest/docs/resources/network_rules)

chore: update tf docs

---

mgc/sdk/openapi/operation.go

Alterado a forma que parametros do tipo `query param` são incluidos na montagem do http request.
Foi identificado que o request era enviado passando `nil` como valor do parametro. Isso só acontecia quando a spec **não** possuia valor padrão para o parametro.
O tratamento é semelhante ao aplicado no commit `11cd1b5d227411d8707e44ef33c664bcb3b129fd` .
_
Antes do ajuste:
Após o ajuste:

chore: change query-param

---

mgc/sdk/openapi/operation.go

Introduces the following changes:
- Adds a new security schema named `HTTPBearer` to the list of supported authentication methods (`isSupportedScheme` function).
- Defines a constant `HTTPBearer` with the value `"httpbearer"`.
These changes extend the existing OpenAPI security mechanisms by including support for HTTP Bearer authentication.
Fixes #[issue_number]

feat: Add openapi security schema HTTPBearer

---

mgc/terraform-provider-mgc/docs/resources/dbaas_instances.md
mgc/terraform-provider-mgc/examples/resources/mgc_dbaas_instances/resource.tf

This pull request includes updates to the `mgc_dbaas_instances` resource in both the documentation and example Terraform configuration files. The changes involve replacing the `flavor_id` attribute with new attributes for `engine_id` and `instance_type_id`.
Updates to `mgc_dbaas_instances` resource:
* [`mgc/terraform-provider-mgc/docs/resources/dbaas_instances.md`](diffhunk://#diff-46c0c6e76a1521b7d31d3e324b96f7da96ef16028dc225cc4a92858f607e6cccL18-R22): Removed `flavor_id` and added `engine_id` and `instance_type_id` with sample values and comments to check available versions and engines.
* [`mgc/terraform-provider-mgc/examples/resources/mgc_dbaas_instances/resource.tf`](diffhunk://#diff-946647920863685c2b672df1e08c8f4b79608221d054b1074d54d36bb777291dL3-R7): Removed `flavor_id` and added …

chore: update dbaas instance create terraform documentation

---

mgc/terraform-provider-mgc/mgc/resources/mgc_bs_snapshots.go
mgc/terraform-provider-mgc/mgc/resources/mgc_bs_volumes.go
mgc/terraform-provider-mgc/mgc/resources/mgc_vm_instances.go
mgc/terraform-provider-mgc/mgc/resources/mgc_vm_snapshots.go

- removing plan modifiers from terraform fields with UseStateForUnkown that are dynamic
- Fix the error message when renaming a vm or any other resource that were using the UseStateForUnkown
ok
```shell
❯ tfa -auto-approve
data.mgc_virtual_machine_types.available_types: Reading...
data.mgc_virtual_machine_images.available_images: Reading...
data.mgc_virtual_machine_instances.all_instances: Reading...
mgc_virtual_machine_instances.tc1_basic_instance: Refreshing state... [id=43a05476-e461-449c-b79b-ac9e16823fcd]
data.mgc_virtual_machine_images.available_images: Read complete after 2s …
```

fix: removing plan modifiers from terraform fields with UseStateForUnkown that are dynamic

---

.github/workflows/upload-docs.yaml

chore: remove public read permissions step from upload-docs workflow

chore: remove public read permissions step from upload-docs workflow

---

mgc/sdk/static/object_storage/common/session.go

Escape the "%" symbol 
Manually tested by trying to create a bucket with the name "foo%bar" and exhaustively in [s3-tester](https://github.com/marmotitude/s3-tester)
Before
`Error: (unknown) 404 Not Found`
After
`Error: (InvalidBucketName) 400 Bad Request - The specified bucket is not valid.`

fix escape on create bucket

---

mgc/sdk/static/object_storage/common/delete.go

Change the delete object so that when there is more than 1 file, do a post/batch delete and when there is only 1 file, do a delete
Manually tested sending unique file and list of files.

fix: delete objects to use single delete

---

mgc/sdk/go.mod
mgc/sdk/static/object_storage/common/delete.go
mgc/sdk/static/object_storage/common/object-lock.go
mgc/sdk/static/object_storage/objects/object-lock/set.go

feat [cli] - object storage locking

---

mgc/cli/docs/block-storage/snapshots/copy/help.md
mgc/lib/go.mod
mgc/lib/products/block_storage/volume_types/list.go
mgc/lib/products/block_storage/volumes/create.go
mgc/lib/products/block_storage/volumes/get.go
mgc/lib/products/block_storage/volumes/list.go
mgc/lib/products/doc.go
mgc/sdk/openapi/openapis/block-storage.openapi.yaml
mgc/spec_manipulator/cli_specs/block-storage.jaxyendy.openapi.json
mgc/spec_manipulator/cli_specs/conv.block-storage.jaxyendy.openapi.json
mgc/terraform-provider-mgc/docs/data-sources/block_storage_volume.md
mgc/terraform-provider-mgc/docs/data-sources/block_storage_volumes.md
mgc/terraform-provider-mgc/docs/resources/block_storage_volumes.md
mgc/terraform-provider-mgc/go.mod
mgc/terraform-provider-mgc/mgc/datasources/mgc_bs_volume.go
mgc/terraform-provider-mgc/mgc/datasources/mgc_bs_volumes.go
mgc/terraform-provider-mgc/mgc/resources/mgc_bs_volumes.go
mgc/terraform-provider-mgc/tests/block-storage/main.tf

add encryption support for block storage volumes
```shell
❯ tfa -auto-approve
data.mgc_block_storage_volumes.volumes_data: Reading...
data.mgc_block_storage_volumes.volumes_data: Read complete after 1s
Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
+ create
<= read (data resources)
Terraform will perform the following actions:
<= data "mgc_block_storage_snapshot" "snapshot_data" {
+ availability_zones = (known after …
```

feat: add encryption support for block storage volumes

---

.pre-commit-config.yaml

```shell
❯ g commit -m 'chore: upgrade precommit to v5'
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check "cli dump-tree" output.............................................Passed
check "cli doc" outputs..................................................Passed
apply-oapi-customizations................................................Passed
oapi-index-gen...........................................................Passed
generate terraform documentation.........................................Passed
check terraform examples.................................................Passed
check terraform documentation subcategory................................Passed
check …
```

chore: upgrade precommit to v5

---

mgc/terraform-provider-mgc/mgc/resources/mgc_bs_volumes.go

When not passing a value for az in block storage volumes the sdk has sending the field with a empty value.

fix: handling of availability zones for block storage volumes

---

mgc/terraform-provider-mgc/mgc/resources/mgc_bs_volumes.go
mgc/terraform-provider-mgc/mgc/resources/mgc_net_vpcs.go
mgc/terraform-provider-mgc/mgc/resources/mgc_vm_instances.go
mgc/terraform-provider-mgc/mgc/tfutil/planmodifiers.go

* Added error handling for VPC creation in `mgc_net_vpcs.go` to capture and log errors when the VPC creation status contains "error".
* Updated `mgc_bs_volumes.go` to include a custom plan modifier `ReplaceIfChangeAndNotIsNotSetOnPlanBool` for boolean attributes.
* Modified the VM instance creation logic in `mgc_vm_instances.go` to check if `VpcId` is not an empty string before setting the network VPC ID.

fix: terraform virtual machine vpc error, block storage recreation and network vpc creating with error

---

mgc/cli/docs/object-storage/buckets/object-lock/unset/help.md
mgc/sdk/static/object_storage/buckets/object-lock/group.go
mgc/sdk/static/object_storage/buckets/object-lock/unset.go

Implements the 'unset' command for removing object-lock configurations on buckets.
The command sends a PUT request with a customizable XML body to the specified bucket
URL, allowing different combinations of object-lock settings, such as disabling
lock retention or clearing rules.
Changes include:
Addition of the unset command logic and related parameter handling.
Dynamic XML body generation to accommodate different server requirements.
Logging adjustments to display the actual request body sent to the server.

feat: add unset command to remove object-lock configuration from buckets

---

mgc/sdk/static/object_storage/common/list.go

Diferença entre a url da aws-cli e a da mgc-cli
Ao tentar listar um path com prefixo, e o prefixo contendo espaço, ocorre erro de assinatura, a mgc cli esta encodando os espaços como "+" ao inves de "%20"
Como replicar:
- Subir um path que contenha espaços em um bucket
- Tentar lista-lo com o comando abaixo
mgc os objects list "test-space/test with space/"
-Error: (AccessDenied) 403 Forbidden - Credentials or specified url is malformed.
O problema esta no encode da request url
Solved encoding problem by path encoding and not query encoding the url
- **Manual Testing**: Explain the manual testing process, including steps taken and …

fix(list): Bug 1186 - url sign error

---

Makefile
README.md

Creates a easy-to-use Makefile target for local builds.
Useful for people trying branches and pre-releases (snapshots) locally.
- **Manual Testing**: Build a local version following new README instructions.

chore: add local build target to Makefile

---

mgc/cli/docs/virtual-machine/instances/list.md
mgc/cli/docs/virtual-machine/machine-types/list.md
mgc/sdk/openapi/openapis/virtual-machine.openapi.yaml
specs/conv.virtual-machine.jaxyendy.openapi.json
specs/virtual-machine.jaxyendy.openapi.json

Updates VM specs to reflect new default limit for machine types listing
Manual testing on machine-type listing:
```
🛠️  ./dist/mgc_linux_amd64_v1/mgc virtual-machine machine-types list
machine_types:                                                                                                                                                                                                                                                                              
- availability_zones:
- br-se1-a
- br-se1-b
- br-se1-c
disk: 150
gpu: 0
id: 3f1a9f2b-47db-4708-bf82-bea37b54bd4a
name: BV4-16-150
ram: 16384
status: active
vcpus: 4
...
- availability_zones:
- br-se1-b
- br-se1-c
disk: 300
gpu: 1
id: 41852f29-46ef-4987-878f-d352a0f3e338
name: L40x1-BV4-16-300
ram: 16
status: active
vcpus: 4 …
```

Update machine type listing

---

mgc/cli/main.go

Com versão:
Sem versão:
Com `make build-local` - sem versão e sendo um snapshot:

change main.go - version output

---

internal.yaml

Add windows build to local build goreleaser config
Manually by developer. 
- Made a single-target build (`make build-local`) on linux, a linux binary was produced.
- Run goreleaser without single-target flag (`goreleaser build --clean --snapshot -f internal.yaml`) and all targets were produced, including windows binaries for arm64 and amd64
single-target:
multi-target:

chore: add windows build to internal goreleaser

---

mgc/sdk/static/object_storage/common/path_utils.go
mgc/sdk/static/object_storage/objects/upload.go
mgc/sdk/static/object_storage/objects/upload_dir.go

Quando é realizado um upload de um objeto via mgc cli, de um SO Windows, o objeto fica com partes do path e barras inversas na key.
<Key>.\barrainversamgccli.txt</Key>
isso afeta diretamente o list, pois para listar o objeto precisamos utilizar caracteres de escape, do tipo:
.%5Cbarrainversamgccli.txt
Com esse PR, ao fazer o upload de um Windows, a key é normalizada e o objeto é salvo com os padrões corretos de nome.
Testes realizados utilizando os comandos da cli, para upload de objetos, de diretorios e de move objects.
Estão na seção de Screenshots

(OBJS) normalize key when upload objects with backslash (windows default)

---

mgc/cli/docs/object-storage/objects/delete-all.md
mgc/sdk/static/object_storage/common/delete.go

Apply batch_size default when flag not provided
Manually with mgc cli and delve debugger
And s3-specs
Running mgc os objects delete-all {bucket_name}

fix: add required flag to batch_size param
